name: Deploy Docker Compose
on:
  workflow_dispatch:
  workflow_run:
    workflows:
    - "Build, Update docker-compose.yaml"
    types:
    - completed
    branches:
    - main
jobs:
  deploy:
    name: Deploy using Docker Compose
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch'}}
    steps:
    - name: Join tailscale network
      uses: tailscale/github-action@v2
      with:
        authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

    - name: Debug Tailscale
      run: |
        tailscale status
        ping -c 4 ${{ secrets.TAILSCALE_SERVER_IP }}
    - name: Check SSH port
      run: |
        nc -zv ${{ secrets.TAILSCALE_SERVER_IP }} 22

    # - name: SSH and Deploy
    #   uses: appleboy/ssh-action@v1.2.5
    #   with:
    #     host: ${{ secrets.TAILSCALE_SERVER_IP }}
    #     username: deploy
    #     key: ${{ secrets.SSH_KEY }}
    #     script: sudo /usr/local/bin/deploy/deploy-rohitkalyan.sh
    - name: SSH and Deploy
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.TAILSCALE_SERVER_IP }}
        username: deploy
        key: ${{ secrets.SSH_KEY }}
        port: 22
        timeout: 30s
        command_timeout: 10m
        script_stop: true
        script: |
          echo "Connected"
          sudo /usr/local/bin/deploy/deploy-rohitkalyan.sh
