name: Deploy Docker Compose
on:
  workflow_dispatch:
  workflow_run:
    workflows:
    - "Build, Update docker-compose.yaml"
    types:
    - completed
    branches:
    - main
jobs:
  deploy:
    name: Deploy using Docker Compose
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch'}}
    steps:
    - name: Join tailscale network
      uses: tailscale/github-action@v2
      with:
        authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

    - name: SSH and Deploy
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.TAILSCALE_SERVER_IP }}
        username: deploy
        key: ${{ secrets.SSH_KEY }}
        script: sudo /usr/local/bin/deploy/deploy-rohitkalyan.sh
